# Generated by Django 3.0.5 on 2020-06-15 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comida', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cantidadComidaOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadComida', models.IntegerField(default=1)),
                ('idComida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.Comida')),
            ],
        ),
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dirrec', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('estado', models.CharField(choices=[('CT', 'EN CARRITO'), ('PD', 'PENDIENTE'), ('LT', 'LISTA'), ('EC', 'EN CAMINO'), ('ET', 'ENTREGADO'), ('CF', 'CALIFICADO')], max_length=2)),
                ('califi', models.IntegerField(null=True)),
                ('comida', models.ManyToManyField(through='usuarios.cantidadComidaOrden', to='comida.Comida')),
                ('dirr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.direccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Órdenes',
            },
        ),
        migrations.AddField(
            model_name='cantidadcomidaorden',
            name='idOrden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='usuarios.Orden'),
        ),
    ]
