# Generated by Django 3.0.5 on 2020-05-28 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cantidadComidaOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadComida', models.IntegerField()),
                ('idComida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.Comida')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('califi', models.IntegerField(null=True)),
                ('comida', models.ManyToManyField(through='usuarios.cantidadComidaOrden', to='comida.Comida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Órdenes',
            },
        ),
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dirrec', models.TextField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cantidadcomidaorden',
            name='idOrden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Orden'),
        ),
    ]
