# Generated by Django 3.0.5 on 2020-05-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='califi',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
