# Generated by Django 3.0.3 on 2020-06-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidadcomidaorden',
            name='cantidadComida',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cantidadcomidaorden',
            name='idOrden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_elems', to='usuarios.Orden'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('CT', 'CARRITO'), ('PD', 'PENDIENTE'), ('LT', 'LISTA'), ('EC', 'EN CAMINO'), ('ET', 'ENTREGADO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
